### ISSUE TITLE
noble.reset() generates an error

### ISSUE THREAD

**Issue by majordo** [abandonware/noble#140]
noble.reset() gives me this error:
```
TypeError: noble.reset is not a function
    at Rilevatore.resetAsync (/home/pi/kiosk-cio/rilevatore-presenze/server/server.js:538:15)
    at Timeout._onTimeout (/home/pi/kiosk-cio/rilevatore-presenze/server/server.js:743:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
What's wrong?

**Comment by atrovato** [comment]
This will be on next version, I'm waiting for too :)

**Comment by majordo** [comment]
Any release date?

**Comment by titaniumwhite** [comment]
I'm looking for noble.reset() too! Has it been implemented yet?
