### ISSUE TITLE
unable to  override NOBLE_HCI_DEVICE_ID

### ISSUE THREAD

**Issue by rabee05** [abandonware/noble#147]
I have 2 adapters  hci1 and hci1, I got an error when I run 
sudo NOBLE_HCI_DEVICE_ID=1 node  test.js

internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/user1/code/node/test/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user1/code/node/test/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

I ran npm rebuild seems to rebuild fine, but I still get the same error. Any help/tips very much appreciated 

I have bluez  version 5.50

Thanks,
RZ

**Comment by rabee05** [comment]
I was able to run fine without sudo 

sudo NOBLE_HCI_DEVICE_ID=1 node spoo2.js

I am not sure why sudo was causing the issue, any explanation is appreciated.
