### ISSUE TITLE
TypeError: Cannot set property 'mtu' of undefined

### ISSUE THREAD

**Issue by fisherwise** [abandonware/noble#164]
Getting this error consistently when 2 nodejs program starts discovery simultaneously

```
at Noble.onMtu (/home/pi/homebridge-soma-shades/node_modules/@abandonware/noble/lib/noble.js:564:18)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onMtu (/home/pi/homebridge-soma-shades/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:277:8)
    at Gatt.emit (events.js:315:20)
    at Object.callback (/home/pi/homebridge-soma-shades/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:329:10)
    at Gatt.onAclStreamData (/home/pi/homebridge-soma-shades/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:133:26)
    at AclStream.emit (events.js:327:22)
    at AclStream.push (/home/pi/homebridge-soma-shades/node_modules/@abandonware/noble/lib/hci-socket/acl-stream.js:33:10)
    at NobleBindings.onAclDataPkt (/home/pi/homebridge-soma-shades/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:288:15)
    at Hci.emit (events.js:315:20)
```

Running on Pi 4
```
pi@raspberrypi:~ $ node -v
v14.15.4
pi@raspberrypi:~ $ npm -v
6.14.11
```

**Comment by fisherwise** [comment]
created a simple PR for it #165
