### ISSUE TITLE
Subscription to Xiaomi Mi Kettle statusCharacteristic crashes with ERR_OUT_OF_RANGE

### ISSUE THREAD

**Issue by Hypfer** [abandonware/noble#19]
I'm trying to connect to my bluetooth enabled kettle using noble. Everything works fine up to the point I'm subscribing to the status update topic using `.notify(true, err => {console.log(err)})`

Editing gatt.js to ignore the out of bounds read results in a perfectly fine stream of status updates from the kettle.

Is this a Bug in Noble? Is this a non-standard Implementation by Xiaomi?

https://github.com/abandonware/noble/blob/master/lib/hci-socket/gatt.js#L625
`data` looks like this: `<Buffer 09 03 3e 00 00>`
```
internal/buffer.js:55
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readUInt16LE (internal/buffer.js:134:5)
    at Gatt.<anonymous> (/home/hypfer/WebstormProjects/ble_things/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:625:24)
    at Gatt.onAclStreamData (/home/hypfer/WebstormProjects/ble_things/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:132:26)
    at AclStream.emit (events.js:187:15)
    at AclStream.push (/home/hypfer/WebstormProjects/ble_things/node_modules/@abandonware/noble/lib/hci-socket/acl-stream.js:35:10)
    at NobleBindings.onAclDataPkt (/home/hypfer/WebstormProjects/ble_things/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:286:15)
    at Hci.emit (events.js:182:13)
    at Hci.onSocketData (/home/hypfer/WebstormProjects/ble_things/node_modules/@abandonware/noble/lib/hci-socket/hci.js:497:14)
    at BluetoothHciSocket.emit (events.js:182:13)
```

**Comment by rzr** [comment]
Is this related ? if not please also forward this issue upstream and cross link here.
