### ISSUE TITLE
No longer installs properly

### ISSUE THREAD

**Issue by stormbytes** [abandonware/noble#199]
Wondering if it's complaining that I'm on Node v.14.x ?

npm install @abandonware/noble
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /Users/storm/Library/Mobile Documents/com~apple~CloudDocs/dev/sandbox/noblejs/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   CXX(target) Release/obj.target/binding/lib/mac/src/noble_mac.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.4.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/storm/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/storm/Library/Mobile Documents/com~apple~CloudDocs/dev/sandbox/noblejs/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/storm/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/storm/Library/Caches/node-gyp/14.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/storm/Library/Caches/node-gyp/14.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/storm/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/storm/Library/Caches/node-gyp/14.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/storm/Library/Mobile Documents/com~apple~CloudDocs/dev/sandbox/noblejs/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/dev/sandbox/noblejs/node_modules/node-addon-api'
npm ERR! clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/dev/sandbox/noblejs/node_modules/napi-thread-safe-callback'
npm ERR! make: *** [Release/obj.target/binding/lib/mac/src/noble_mac.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/storm/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/Users/storm/.nvm/versions/node/v14.4.0/bin/node" "/Users/storm/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/storm/Library/Mobile Documents/com~apple~CloudDocs/dev/sandbox/noblejs/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v14.4.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/storm/.npm/_logs/2021-03-29T21_50_36_040Z-debug.log

-----------

Debug Log:

→ tail /Users/storm/.npm/_logs/2021-03-29T21_50_36_040Z-debug.log
394 error gyp ERR! stack     at ChildProcess.onExit (/Users/storm/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
394 error gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
394 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
394 error gyp ERR! System Darwin 19.6.0
394 error gyp ERR! command "/Users/storm/.nvm/versions/node/v14.4.0/bin/node" "/Users/storm/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
394 error gyp ERR! cwd /Users/storm/Library/Mobile Documents/com~apple~CloudDocs/dev/sandbox/noblejs/node_modules/@abandonware/noble
394 error gyp ERR! node -v v14.4.0
394 error gyp ERR! node-gyp -v v7.1.2
394 error gyp ERR! not ok
395 verbose exit 1

**Comment by halbano** [comment]
I am having the same issue. Might be something related with the node version?
