### ISSUE TITLE
Several occurences of range errors when reading from Buffers

### ISSUE THREAD

**Issue by AlCalzone** [abandonware/noble#84]
I've gotten reports from users who are getting the following errors due to unchecked buffers in noble:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 6
	at BluetoothHciSocket.emit (events.js:310:20)
	at Hci.onSocketData (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js:436:27)
	at Uint8Array.readUInt8 (internal/buffer.js:243:5)
	at boundsError (internal/buffer.js:77:9)
```
and
```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
	at BluetoothHciSocket.emit (events.js:310:20)
	at Hci.onSocketData (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js:451:18)
	at Uint8Array.readUInt16LE (internal/buffer.js:234:5)
	at boundsError (internal/buffer.js:77:9)
```

**Comment by kylerove** [comment]
I think I've been getting similar errors. Trying to read a particular characteristic from a dimmer:

```
[5/31/2020, 10:07:46 PM] [Phormalab South] Starting bluetooth scan...
[5/31/2020, 10:07:46 PM] [Phormalab South] Found dimmer for Phormalab South, connecting...
[5/31/2020, 10:07:49 PM] [Phormalab South] Bluetooth connection made, discovering services...
[5/31/2020, 10:07:49 PM] [Phormalab South] Found dimmer characteristic: 00008e02a37de411bedb50ed7800a5a5
[5/31/2020, 10:07:49 PM] [Phormalab South] Starting read from dimmer (00008e02a37de411bedb50ed7800a5a5)
[5/31/2020, 10:07:50 PM] [Phormalab South] Executing bluetooth 'read' callback on dimmer
[5/31/2020, 10:07:50 PM] [Phormalab South] Got success response from dimmer
[5/31/2020, 10:07:50 PM] [Phormalab South] <Buffer 00>
[5/31/2020, 10:11:42 PM] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readInt32LE (internal/buffer.js:381:5)
    at PhormalabAccessory.<anonymous> (/home/ubuntu/homebridge-phormalab/index.js:274:27)
    at Characteristic.onRead (/home/ubuntu/node_modules/@abandonware/noble/lib/characteristic.js:45:9)
    at Characteristic.emit (events.js:315:20)
    at Noble.onRead (/home/ubuntu/node_modules/@abandonware/noble/lib/noble.js:414:20)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onRead (/home/ubuntu/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:391:8)
    at Gatt.emit (events.js:315:20)
    at Object.callback (/home/ubuntu/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:537:14)
[5/31/2020, 10:11:42 PM] Got SIGTERM, shutting down Homebridge...
```

When I echo the read buffer into the log, you can see it is just `<Buffer 00>` and it is like this for every characteristic I read. When I query the same device with LightBlue iOS app, it is clearly a hex value (in this particular characteristic) like **0x010164**. I'm trying to read with `buffer.readUInt16LE(0);` and get the above out of bounds error (which makes sense if the buffer is only **00**).
